neherlab/treetime

treetime/seq_utils.py
treetime/treeanc.py

In `seq_utils.py` `seq2array` the alignment is always converted to uppercase. For sequences this good, as prevents mismatches between upper- and lower-case base. However for ancestral reconstruction of other traits like location, these are given 1-char 'codes' and passed as an alignment. Both upper- and lower-case characters are used to code different locations. Currently, converting to uppercase remaps any country that was mapped to a lower-case char to some other country.
This fix allows the user to specify in `TreeAnc` (and all inheriting classes) `convert_upper` (True or False, default=True). When used for ancestral state reconstruction ('mugration' in Augur/Augurlinos), this should be set to False. 
Only datasets with >32 countries would be affected (I think), as the char-mapping …

Fixing always convert to uppercase bug

---

.gitignore

@rneher ---
Mac OS continually creates a `.DS_Store` file in the `treetime/` submodule within `augur/`. This then causes issues with the repo looking like it has unstaged changes. This PR fixes the small issue.

Include OS files in gitignore

---

treetime/treeanc.py

At the end of `process_alignment_dict` a constant site for every `base` in `states` is added to the alignment patterns and reduced alignment. However, some alignments may not have a constant site for that base. The most likely case is that the alignment doesn't have a site that's all gaps ('-').
Under the current code, this is added to the alignment anyway, but with the 'locations where this pattern is found in the real alignment' as an empty array (`[]`) - this then causes an error when creating a map to compress a sequence in `make_reduced_alignment`.

Fix for vcf_new VCF constant site parsing

---

treetime/vcf_utils.py

Introduces new script `vcf_utils.py` containing the functions `read_vcf` and `write_vcf`, which provide in/out for .vcf/.vcf.gz files in the data-structure expected by/received from TreeTime.
Compression is detected from the file ending.
Use example:
`from treetime.vcf_utils import read_vcf, write_vcf`
_Note:_
Output (status, warnings, errors) is not currently provided via the standard TreeTime logging system.

Read and Write VCF files

---

setup.py
treetime/version.py

…so the Python 3 version on this branch, py3, is distinguishable from
the Python 2 version on master.  In particular this lets requirements in
other places use a specific version to distinguish the Python-compat
branches.
This is the most conservative version bump.  At some point it'd be nice
to switch to semantic versioning.

Bump version to 0.4.0

---

doc/source/gtr.rst
doc/source/index.rst
doc/source/seq_utils.rst
doc/source/treeanc.rst
treetime/clock_tree.py
treetime/gtr.py
treetime/seq_utils.py
treetime/treeanc.py
treetime/treetime.py
treetime/vcf_utils.py

Should now run without errors and with decorated functions handled correctly. Added new vcf-specific functions, and did a quick sweep to correct typos, improve clarity, and vaguely standardise to numpy autodoc style. 
The command-line functions on the index were updated to include the description from their argparse.
No code is changed, only comments.

Cleaning up & standardizing autodoc

---

bin/treetime
treetime/clock_tree.py
treetime/treeanc.py
treetime/treeregression.py
treetime/treetime.py
treetime/wrappers.py

This PR adds functionality to calculate the effect of rate uncertainty on the ancestral dates. This is done by repeating the calculation at rates +/- standard deviation from the ML rate. The resulting variation in dates can then be folded into confidence intervals.

Rate variation

---

treetime/vcf_utils.py

Prevents errors when VCF reference FASTA is in lowercase. FASTA input is already converted to uppercase when read in.
Should resolve issue #82

Convert VCF ref to uppercase when read in

---

test/test_treetime.py
treetime/__init__.py
treetime/treeanc.py

This PR is part bug-fix and part adding functionality to allow recovery of ambiguous bases for Fasta input (previously only available for VCF input).
**Bug Fix**
When a column has only two unique states and one is ambiguous ('AAAANNA'), the ambig sites are replaced by the other base (so 'AAAANNA' is processed as if it is 'AAAAAAA'). However, ambig sites are only replaced in `str_pat` (line [597](https://github.com/neherlab/treetime/blob/d9448934525e66413c851b7aa11690054ea397a8/treetime/treeanc.py#L597) of treeanc.py), the string of the column, and not in `pattern`, the array of the column.
`str_pat` is then used check if the pattern has been seen before (line [606](https://github.com/neherlab/treetime/blob/d9448934525e66413c851b7aa11690054ea397a8/treetime/treeanc.py#L606)) and add it to …

Ambiguous Base Recovery for Fasta

---

treetime/treeanc.py

If TreeTime is handed a Newick tree with just a topology, the `_calc_dist2root` function will fail reporting:
`TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'`
This resulted from the branch_length attr existing but being set to None. With this fix TreeTime now works with just an input topology.
You can reproduce the original error by running https://github.com/nextstrain/zika-tutorial, but modifying the intermediate `tree_raw.nwk` to remove all branch lengths `:0.303`, etc...

Include safety checks in _calc_dist2root for missing branch lengths

---

treetime/wrappers.py

This PR avoid overwriting the content of the automatically generated output directories by adding a '-0001' style counter to the date. This should address issue #95

add counter suffix if outdirectory already exist

---

treetime/gtr.py
treetime/wrappers.py

This PR generalized the way weights are handled in discrete trait reconstruction. It now allows to specify weights of unobserved states. In addition, the GTR inference is done slightly differently when the equilibrium frequencies are fixed. in this case, we use the expected time in tree instead of observed time in tree for different states. This is more stable.

Unobserved states

---

treetime/wrappers.py

While running the latest nCoV build, ran into a bug where the `alphabet`/`reverse_alphabet` did not contain the last `unique_trait`. 
This turned out to be a discrepancy in counting/not-counting/including/not-including the 'missing data' value. 
This PR fixes this (@rneher actually made these changes), but perhaps could be made more robust before merging. At least provides a record of the problem and the fix.

Fix missing data size of alphabet bug

---

.pylintrc

Adds pylint configuration.
I excluded most of the stylistic and opinionated rules and only left something that looks dangerous or is simple to fix. And there is still quite a few things being reported.
Install `pylint`:
```
pip3 install --user --upgrade pylint
```
Run on `treetime/` directory:
```
reset; pylint treetime/**/*.py
```
(`reset` cuts off the terminals' scrolling history)
If necessary, a rule can be silenced by adding it to the list in `.pylintrc`:
https://github.com/neherlab/treetime/blob/ba2be021a120851833921f1a78acc38fbb4fab62/.pylintrc#L5-L56
Or disabled and then enabled in a block:
```
...
```

add pylint configuration

---

treetime/distribution.py
treetime/gtr.py
treetime/node_interpolator.py
treetime/sequence_data.py

This is an initial naive attempt to speed up the inference step by moving as much work as possible into numpy and otherwise vectorizing work where possible. The hotspots to work on were determined by profiling the following command, adapted from test/command_line_tests.sh:
`treetime --aln treetime_examples/data/tb/lee_2015.vcf.gz --vcf-reference treetime_examples/data/tb/tb_ref.fasta --tree treetime_examples/data/tb/lee_2015.nwk --clock-rate 1e-7 --dates treetime_examples/data/tb/lee_2015.metadata.tsv`
Profiling inormation was retrieved like this: `python3 -c'import pstats; p = pstats.Stats("treetime_tottime.cprofile"); p.strip_dirs().sort_stats("tottime").print_stats(42)'`
In my tests, this brings a modest (~10%) but stable speedup of the inference loop.
Relevant to …

Inference speedups

---

treetime/treetime.py

idq_n accepts float and it makes sense that it does. Outlier removal is continuous. It's just that the documentation is more restrictive than the code.

update docstring: idq_n accepts floats

---

treetime/sequence_data.py
treetime/wrappers.py

This PR avoids detour via in mugration via a biopython alignment and instead passes in sequences are compressed sequences which are handled by treetime internally as unicode arrays.

fix: Bio.Seq.Seq represents sequences as bytes now. 

---

treetime/treeanc.py

The joint likelihood function for ancestral sequence reconstruction stores two matrices per node in a given tree including a) the likelihood per state and site in the alignment (`joint_Lx`) and b) the indices of optimal states per parent state and site in the alignment (`joint_Cx`). The current implementation stores the likelihoods as double precision floats (`float64`) and the state indices as 64-bit signed integers. With larger trees (~6,000 tips and ~12,000 total nodes), the size of these annotations on the tree causes memory usage to spike to 12 GB during ancestral sequence reconstruction. These memory spikes can cause augur refine jobs to be killed when multiple are running at once (e.g., on AWS Batch).
This PR makes three minor modifications to the joint likelihood function to …

Reduce memory required for ancestral sequence inference

---

.gitignore
treetime/treeanc.py

Resolves #177 
**Context**
When doing ancestral state reconstruction with a tree that has many tips without alignment (>1/3), treetime throws an error.
This PR introduces a new constructor parameter `ignore_missing_alns=False` that defaults to `False` in a backward compatible manner. Setting it to true means that no error is raised even when more than 1/3 of tips don't have alignments attached.
This extends use cases.
**Testing**
Tested with my script that needs this feature and both `True` and `False` do exactly what they're supposed to do. No error vs error.
**Usage**
```python
tt = TreeAnc(tree=tree, aln=alignment, ignore_missing_alns=True)
```
**Other commits**
I noticed that defaults weren't documented in numpy style in the docs, so I fixed it where I saw it. Also fixed a typo and …

Add ignore_missing_alns option to TreeAnc to extend use cases

---

treetime/wrappers.py

Pull request to add a branch_mutations.txt output file to treetime ancestral. We've found this to be useful when we have large trees with lots of mutations as the annotated_tree.nexus file becomes very large to read in. The proposed new output file contains each inferred mutation and the branch it occurred on as a text file

Add new output file to ancestral containing branch mutations

---

README.md
docs/source/index.rst

This removes Travis CI badge and places GitHub Actions badge in:
- readme
- index file of the docs

docs(readme): replace build status badge

---

docs/source/tutorials/timetree.rst

I was trying to understand the numeric date format output in the NEWICK tree and based on #128 and the [source code for `numeric_date()`](https://github.com/neherlab/treetime/blob/f5a4e72584dee7f45ffa7c9a54837532b14614ca/treetime/utils.py#L145) this was my understanding of it. 
Hope the update to the docs seems suitable. 
And thanks for developing the package!

clarify numeric date documentation

---

treetime/wrappers.py

When running `treetime ancestral` the file output names have `{}` inserted.
This leads to the output file names `ancestral_sequences{}.fasta` and `annotated_tree{}.nexus`.
This pull request modifies the default tree suffix of the `export_sequences_and_tree` function to remove the braces.

fix for minor file name issue

---

treetime/wrappers.py

The `clock_deviation` had undefined value on this line
https://github.com/neherlab/treetime/blob/a76ac2b9f1d04374d98cce2b00d837f5867b150d/treetime/wrappers.py#L1074
After a short Slack discussion we decided that it should be `0.0`, for consistency with the non-terminals and also taking into consideration the comment just above the loop:
```
Dates of nodes that didn't have a specified date are inferred from the root-to-tip regression
```

fix: set clock deviation to 0 for terminals without date constraint

---

treetime/distribution.py
treetime/gtr.py

When trees with long branches are given as input to `treetime` overflow errors and other bugs can occur, these errors should be better handled with commentary. See: https://github.com/nextstrain/augur/issues/1013. 
Resolves https://github.com/nextstrain/augur/issues/1013
I tested these out by making `treetime` throw an error when running data, e.g. triggering the exception in `_exp_lt` by adding ```log_val = np.ones(len(log_val))*750```, or the exception in `calc_fwhm` by adding ```tmp = []```. I also ran it on data with long branches (https://github.com/nextstrain/augur/issues/1013)... but potentially there is a better way to do this...

Properly raise numerical instability errors occurring due to problematic input trees

---

treetime/__init__.py
treetime/clock_tree.py
treetime/distribution.py
treetime/gtr.py
treetime/treeanc.py
treetime/treetime.py
treetime/utils.py
treetime/wrappers.py

https://github.com/nextstrain/augur/issues/1032
https://github.com/nextstrain/augur/pull/1033
Building on @victorlin's suggestions in : https://github.com/neherlab/treetime/compare/44e7c56a1d10baa3d4dcdf07b5c7cd55d6d651e9...2632d96144ada719a33f966cc11c5bc118c987a4 I have made a couple minor changes to TreeTime's error handling process: 
- more consistent labeling of error classes: rename errors due to incorrect input data or incorrect use of treetime as one of the three predefined TreeTime error classes: `MissingDataError`, `UnknownMethodError` and `NotReadyError`
- add new `TreeTimeError` class for errors that might be due to input data not matching with assumptions or unknown behavior (potential bug): `TreeTimeOtherError`. 
- call `treetime.run` in a wrapper to catch all errors with …

Improve Error Handling in TreeTime

---

treetime/__init__.py
treetime/treetime.py

Building on https://github.com/neherlab/treetime/pull/206 I added some suggestions that Victor made
- change the name of `TreeTimeOtherError` to `TreeTimeUnknownerror` to be more clear for users
- change argument in `run` function to `raise_uncaught_exceptions` from `augur` so more clear and can be used with other programs
- some minor fixes regarding print statement location 
This can now be used from augur and will work with: https://github.com/nextstrain/augur/pull/1033

TreeTime Error Log - add Victor's suggestions

---

treetime/clock_tree.py
treetime/distribution.py
treetime/treeregression.py

this should address the curious slow down of the marginal time tree calculation. it was due to an explosion in the number of grid points when a large number of distributions were multiplied (taking the union of all grid points). This is now fixed by using a running average of the union of the grid points with the same number of points and the average distribution.

limit number of grid points when multiplying distributions

---

test/command_line_tests.sh
treetime/argument_parser.py
treetime/wrappers.py

Currently we use the value 50 as the default number of generations per year when estimating merger rate trajectories via the CLI. However, as different organisms have a different generation per year rate it would be nice to add this as a parameter, especially when the output is a desired skyline plot of the inverse rate of coalesence scaled by the number of generations per year. 
https://github.com/neherlab/treetime/issues/210
A CLI test has been added to the `command_line_tests.sh` file.

Feature: input generation per year via CLI for skyline and N_e calculations

---

test/test_treetime.py
treetime/wrappers.py

Fixes an issue that emerged when running `augur traits` with flu data where strains with known states in their metadata were getting states inferred as if they were unknown. For example, the screenshot below shows a specific strain from Oman that had "West Asia" in its `region` column of the metadata, but the traits node data included an inferred region of "North America".
To debug this issue, I added an ipdb checkpoint to the `augur traits` module locally [just after the `reconstruct_discrete_traits` function was called and traits assigned to nodes](https://github.com/nextstrain/augur/blob/7f968ce7a0ebf1226bf1a5e99717f0175ae55159/augur/traits.py#L83). I ran the following commands to recreate the logic of that function in the ipdb REPL:
```python
>>> unique_states = set(traits.values()) …
```

Fix reconstruction of discrete traits with missing data

---

treetime/treeanc.py

https://github.com/nextstrain/augur/issues/1062  - general bug that if a node sequence is not in the alignment treetime will print a warning and then crash instead of throwing an exception. In this issue there was an unnamed terminal node in the tree ('None') with no sequence data. 
Reproduce error either with large tree in the issue above or by removing a terminal sequence from the `treetime_examples/data/h3n2_na/h3n2_na_20.fasta` , the command 
```treetime --aln treetime_examples/data/h3n2_na/h3n2_na_20.fasta --tree treetime_examples/data/h3n2_na/h3n2_na_20.nwk --dates treetime_examples/data/h3n2_na/h3n2_na_20.metadata.csv --confidence --covariation ```
should throw a missing data error, the command 
```treetime --aln treetime_examples/data/h3n2_na/h3n2_na_20.fasta --tree …
```

Improve error handling of missing terminal sequences

---

treetime/clock_tree.py
treetime/node_interpolator.py

https://github.com/nextstrain/augur/issues/1057 The monkey pox build has branches where the node distributions are much smaller than the branch distributions and the fft fails as the grid is not coarse enough. 
- In these cases where the node distributions are much smaller than the branch distributions we should treat the node distribution as a delta function at the peak pos $T_n$ of that distribution and instead of using the fft to convolve the two distributions return the result of the branch length interpolator convolved with a delta function (this is for the inverse time case). 
$$C(t) = \int b(\tau) H(t- \tau) d\tau = C(t) = \int b(\tau) \delta([t - \tau] - T_n) d\tau =b(t - T_n)$$
we can also add the case if the branch length interpolator distribution is too small 
$$C(t) = \int …

convolve_fft: convert to delta function if distributions too narrow 

---

treetime/vcf_utils.py

https://github.com/neherlab/treetime/issues/218
Thanks to @andreott for finding and fixing this bug!
Error can be reproduced by adding the final index of the reference sequence to the positions vector in the `write_vcf` function, i..e `positions = np.append(positions, [len(ref)-1])` and running 
```treetime ancestral --aln data/tb/lee_2015.vcf.gz --vcf-reference data/tb/tb_ref.fasta --tree data/tb/lee_2015.nwk```
in the `treetime_examples` folder.

Bug fix: vcf index error

---

changelog.md
treetime/clock_tree.py
treetime/distribution.py
treetime/node_interpolator.py
treetime/wrappers.py

- when convolving distributions using FFT, we check whether one distribution is much narrower than the other and treat the narrower one as a delta function in that case. This resulted in some loss of accuracy and too tightly constrained nodes. This conditions to trigger this path are now tighter.
- removed left-over debug statements

more strict condition for fall back on delta function convolution

---

treetime/treetime.py

for presence of the merger_model. Now it explicitly checks for the attribute to be present and not None.

The new stochastic_resolve function didn't properly check

---

test/test_treetime.py

Address Pytest warning:
```log
================================================================================================ warnings summary ================================================================================================
test/test_treetime.py::test_seq_joint_reconstruction_correct
/opt/homebrew/Caskroom/miniforge/base/envs/treetime/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but test/test_treetime.py::test_seq_joint_reconstruction_correct returned <treetime.treeanc.TreeAnc object at 0x168882dd0>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
warnings.warn(
test/test_treetime.py::test_seq_joint_lh_is_max …
```

Address Pytest warning

---

.gitignore
changelog.md
test.sh
test/command_line_tests.sh
treetime/CLI_io.py

Fix bug [issue #250](https://github.com/neherlab/treetime/issues/250) introduced in 0.10.0 where treetime fails in absence of an alignment when trying to create an auspice json file.
Other house keeping commits to improve dev workflow (cleaning up test directory etc):
- Add output directories of `bash test/command_line_tests.sh` to .gitignore
- Add failing test for issue #250 to command_line_tests.sh
- chore: Clean up test directory after running tests
Resolves #250

Fix: Only write auspice.json when there is sequence information

---

treetime/gtr.py

The GTR inference was failing when there were no mutations on the tree, i.e. the entire alignment consisted of identical sequences. In that case, there is not data to estimate a model. But the pseudo-count in the GTR inference should in principle then simply result in a flat JC-type model. However, the rate calculation wasn't properly regularized with pseudocounts and ended up being zero, leading to a division by 0 and subsequent NaN type errors. 
fixes: https://github.com/neherlab/treetime/issues/253

fix: regularize mutation rate calculation

---

treetime/utils.py

Document ambiguous date format [2022.23:2022.25] that is accepted
Document types of returned dict's values

docs: Improve docstring of parse_dates

---

test.sh
test/test_vcf.py
treetime/treeanc.py
treetime/vcf_utils.py

This isn't complete yet, but if people wanted to take a look and see if they are happy with the direction this is going in that'd be great!
I still want to take a close look at how insertions are being encoded in the "sequences" output, and is treetime/augur is ok with that (i.e. `data['sequences'][<sample>][<pos>]` is more than one character). And ideally I'd sort out the writing of VCFs as well to both preserve the ploidy representation of alleles and also use the correct chromosome name!

Improve VCF parsing
